name: Docker Image Vulnerability Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t myimage:latest .

    - name: Scan image with Trivy (logs output)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'myimage:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Generate full JSON report with Trivy
      run: |
        docker run --rm -v $(pwd):/app aquasec/trivy image \
          --format json \
          -o /app/trivy-report.json \
          myimage:latest

    - name: Upload Trivy report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-report
        path: trivy-report.json
